# Generated by Django 4.0.5 on 2022-06-08 00:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0003_remove_transaction_name_transaction_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='from_account',
            field=models.ForeignKey(help_text='sender', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transfer_from', to='ledger.account'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='to_account',
            field=models.ForeignKey(help_text='receiver', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transfer_to', to='ledger.account'),
        ),
    ]
