# Generated by Django 4.0.5 on 2022-06-08 00:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0004_transaction_from_account_transaction_to_account'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='from_account',
        ),
        migrations.AlterField(
            model_name='transaction',
            name='account',
            field=models.ForeignKey(help_text='sender', null=True, on_delete=django.db.models.deletion.CASCADE, to='ledger.account'),
        ),
    ]
