# Generated by Django 4.0.5 on 2022-06-08 00:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0005_remove_transaction_from_account_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='slug',
        ),
    ]
