# Generated by Django 4.0.5 on 2022-06-08 00:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0006_remove_account_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='to_user',
            field=models.ForeignKey(help_text='receiver', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='to_user', to='ledger.user'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='user',
            field=models.ForeignKey(help_text='sender', null=True, on_delete=django.db.models.deletion.CASCADE, to='ledger.user'),
        ),
    ]
